# Generated by Django 5.1.7 on 2025-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parking_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='image_url',
        ),
        migrations.AddField(
            model_name='parking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parkings/'),
        ),
    ]
