# Generated by Django 5.1.7 on 2025-04-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_parking_image_url_parking_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parking',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
