# Generated by Django 5.1.7 on 2025-04-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_savedlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedLocation',
        ),
    ]
