# Generated by Django 5.1.7 on 2025-04-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_savedlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carpark',
        ),
    ]
